# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Abhishek B
email: abhishek.bagati@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  peace out.
baseurl: "blog"
url: "http://iamgr007.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iamgr007
github_username:  iamgr007
stackoverflow_username: iamgr007

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
port: 6969

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
